# Generated by Django 4.1.5 on 2024-10-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appportfolio', '0003_entrevistador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrevistador',
            name='conectado',
            field=models.BooleanField(blank=True, null=True, verbose_name='Conectado'),
        ),
        migrations.AlterField(
            model_name='entrevistador',
            name='seleccionado',
            field=models.BooleanField(blank=True, null=True, verbose_name='Seleccionado'),
        ),
    ]
