# Generated by Django 4.1.5 on 2024-10-30 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appportfolio', '0006_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.ImageField(blank=True, null=True, upload_to='videos/', verbose_name='Video'),
        ),
    ]
