# Generated by Django 4.1.5 on 2024-10-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appportfolio', '0007_alter_imagen_imagen_alter_video_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='user',
        ),
        migrations.RemoveField(
            model_name='video',
            name='user',
        ),
        migrations.AddField(
            model_name='imagen',
            name='comentario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Comentario'),
        ),
        migrations.AddField(
            model_name='video',
            name='comentario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Comentario'),
        ),
    ]
