# Generated by Django 4.1.5 on 2024-11-13 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appportfolio', '0009_alter_video_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ap1', models.CharField(max_length=100)),
                ('ap2', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCurriculumExperiencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appportfolio.curriculum')),
                ('experiencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appportfolio.experiencia')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCurriculumEstudio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appportfolio.curriculum')),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appportfolio.estudio')),
            ],
        ),
    ]
