# Generated by Django 4.1.5 on 2024-11-19 21:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appportfolio', '0011_noticia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('votos_entrevista', models.IntegerField(blank=True, null=True, verbose_name='votos_entrevista')),
                ('votos_empresa', models.IntegerField(blank=True, null=True, verbose_name='votos_empresa')),
                ('media_aspectos', models.IntegerField(blank=True, null=True, verbose_name='Media Aspectos')),
                ('entrevista', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción Entrevista')),
                ('empresa', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción Empresa')),
                ('numvaloraciones', models.IntegerField(blank=True, null=True, verbose_name='Num Valoraciones')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('entrevistador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entrevistadores', to='appportfolio.entrevistador')),
            ],
            options={
                'verbose_name': 'Valoracion',
                'verbose_name_plural': 'Valoraciones',
                'ordering': ['id'],
            },
        ),
    ]
